// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9DXMbt67oX+HsuzM9Z54kS7IsW555c5+TtKlfvtw4SU977JehdrES6xW5h+TaUTP+",
	"73f4tR8SV1rJcj5azbl3GmtJEAQBEAAJ8HMQslnKKFApgtPPQYo5noEErv8iEVBJ5Pz82YX7Xf0cgQg5",
	"SSVhNDgN3k0BuYb2HzEB3glaAVHfUyynQSugeAbBaQlk0Ao4/CcjHKLgVPIMWoEIpzDDaoj/4hAHp8H/",
	"OijQOzBfxcFNNgZOQYJ4jWdQYHZ/3wooyDvGb9YibNutxzcH+CjoMj7BlPyJFWYrcT6jqNwWnT+rwbcK",
	"cSXScp6qHkJyQicanZSzPyCUa6ln2yE1Zg0eOahHoRuHyTqKKTxNs/WL7MA9Dq5ZAmsxFRBmXAnQhLMs",
	"RapPA7Q15EdB2uHzXKGzKfZrEV+A/kgz4LfAG6CumjVB2YB7BFzvDUgQ8gmLCFQ071vzQf0UMiqB6n/i",
	"NE1IqGX84A+h5vI5gE94liag/jkDiSMssUeNoFvgYyYAlX9fUs5t/XcrkHgigtN/f3bfwyQTEnibREEr",
	"uMVJpn4cHQ57g24/bMej0Ul7MArDNh73e+3ReDwa4TiMIzgJ7q/VkqQQKpysuEUK4vHR8AT6UTse4XF7",
	"cHQYtUf4ELePeofHR/HxyaA/HJvlbERkN4FfOZFgSLtIAEtqFDOOMM13rs7Swha7yZddBDvoI69BRDUf",
	"GrZWAwQnHf2/4FrtAxCTT8Fp0Bv1O73hSafb6R70BxsshJ1E03Vw+3EnuG8F/8mYxGIroscJvmXc0Ctk",
	"mepz0gqI4rQRPgmHh8fd9qA7PGoPogFujyLcbR8Pj0+ieNANo1FkSdRohgbLS0XOlfOTDAmQyDTX86to",
	"vy/LW27otlbUj8JijQlYIUNjRqluNR56Zgl8VZqqTdkQtiRtIYm4EqdjJU5amnr9oBVEhENoRyF0wkGI",
	"oBWkjGuEaTYbq23rpGtMM8lClgSngQzTYEsyK+psSWptk1h6K53xpYmsxqxjWIkn7pNjV/WT+XdF7RkF",
	"cd5YIbQCMsMTMFtyYy2S7xwGS5wk7A6isyhSK3yBidNQliusklX/NWr2ejOd1QrSbJyQ8PziLEmYob4m",
	"PMXjpLSdVVjBoLDJpJq3Bo1UJoA/04sdnPdfi/Hhh5uXv76+Hc9+T3+/S8m4P+r+1u/dvJmwycvLJ8lv",
	"/ent+bMfj16RwafXf0yyV2Rw9ObyiYRfp7fh4S+Tiz8Gk5f9D93f5iM2PnzdDe/Su99+fc1/+zVK/nX4",
	"4e73w/83/f35++H5z2/n0a/vX4TPf/oD93+iv//r1fApOZPnP/+ejn9h/2cj2VFct4HAqOYd66GIlFFh",
	"rDn4JIFTnLy2XPHWftxEeNxihYfxqH/cG7Z7cRS2B+PjcXvUHUJ7EEO3dzSI4jCKC7mJGdNr0Wy+i3j6",
	"J50QIRGL0S1OSIRcH7eFmz3ObsRbTrSsJkIOuuE7oifUGx13291eu9t71+2e6v/7PdhEXHLSTDqDzpRM",
	"pjOYdXCv2+30Jp1edzKu6O00+wnPSDJXPEwlJOhfwCi6SLAkNJuhk96w+w794/JmnuAb+GfQUj1EcDpQ",
	"ul3cBKf9biuYpJmClbAJCXHy1Jgl/VYwgxnj8+B0OGgFMxZBogcRktBQolfn/aOu2gymc1Hq1msFt0Aj",
	"pvTG2atnClcH5rB/33ylnaG0coFtI72g1k4msLM1heiJIusfbEo7EYP/i8MZdEI2U0Ssrnm/2x+0u0ft",
	"w9673uC01yuvOR4O4lF/OGofDqHbHhz2+u3xSdRrH/Wj0WF0NByNj8fFmmc0gphQUGxQiZRswD4usqG6",
	"wOEw7B6d4PYJjHF7EB+N26NePGjHwzgej04Oj0dHoelySwRhlNDJpcRSsUjxI0RllmMpUCFxeKMJlbBM",
	"jRNBjLNEKtKoX54yGpOJ+v35NA3nT9T/T89/fpuEh7+8WERxPApHihjHg+Eg6g3G8ckxHHVjfNwfHp50",
	"1YyEmL6A+esZdhrD6G7dHfdGw+MT3D/p9YeD0XE0xv3B+GgQjoa4OxzEOCiiMRrRk1EvGsfddhd3e+0B",
	"xGEbg/LnouPjeBgdDvoDtRw29FTMdQPWLXMijlZzsG0LFR6eb8PBewbeM/BqBt40RlHLvUVQAjkrwrCv",
	"skQfYUvtd/uH7W6/3e+/6/VPu4PT3uG23DnO+v3uoH3b6/SPOsP2JM3aR/2jzslRp3vUPg4hGvSOBmVm",
	"sXtjxMmtcnWCvHVg90QdmjjrddVe+LP9T7/bDa5LG+HrD+fPzs8UWCYMWSJwwRQ2TkB7WkJyZlCkMgta",
	"Qez29QjGBCtX4wY41ZtwQmj2SfsSnGBFXut+qJ+AC7NM/UGna6ZC/oTn5Elw2uu2AsFieYc5fDDtNDpF",
	"5C84DSxpVMdbwmWGEyvB6pv7QQnUBgpR88UaRajbIDnFEmEOSIHBkowTQHdETpGcEoHSBMuY8VknKMe+",
	"9rry8XTlyihcRZG6cyiFyEl/ACfhIGwfnRydtAfjbr89GnWH7cNRFw4HR8PeOD5UvJpgPddetz+4rw/q",
	"fWH1l/NV3d5dDgXShzlMezb827Hh9YZ82MCIrDi2Lji9jVb8hqLTAvTUTDMbvggTAlR2CoPo0WyNYy1W",
	"3dPB0engSInV8mH3p/mMcUZJiCQB3j5ECmAIVAJHYywgQoSil8pqSBlLOk40G50nFaJ5074DITeUlhiw",
	"zLiJ7Dj3PI+YuFjbQ1jTUn81V9pGvhOF/Y79eKpyUyW1baC+Vis1OwD5bllA5JH8b5QBtjrK4ZiaQwSg",
	"aiccjUatQEisPva6w+H9Tg94mvJO+URnAcR3bXDtWShnoa+5ItH3tyLdjv7fQfeBZ7PXW8tuA3PUI8Qe",
	"K2DvMn1rdsB2TLExQ4jKGf33awdUDvy/JSb47q4f7K8SPN5VAr0Hax75HKSc3GIJ5xflOx0dc4priaq+",
	"DPqd/lG3Mxx2eqPhxpcRVhl39vaBk/7v24jby/9e/v8W8n+9mQJoZBDohloVZJTcME7b+tj1Y8g4fJxh",
	"Qj+mN5OPLAWKU/IxZLMZox9xGEIqISqrDV9OhbnyNMUCjQEoct0QphG6I0mCxoDiLIlJkqhfxZyGU84o",
	"y0Qy71zR31iGZniOUpYkSGqIgmU8BA1gxiiRjCMiBTKk1dFJRY4EFBqbzmqMI3tVcTtrCDjXh4yE6vtO",
	"H+38g5b58rFKIUedMYvmyHYJGqv4DaZl0PKwwdsyBjEmag0MfHNhS0+0hRi3tDetIwYCUSaRIgwm9Iri",
	"fHXMpXgUE0iijZkqZnxMogjow6ifg6mhu1IQKOSgD85xIlDE9HSm+Baq01BSShLQJ6ZfY13usEARUAIR",
	"Gs8RzuSUcSLsquhjWCUcY0AhzoRppPCvNLyikt0AdTMkdFKdowhZCi7D4eziPF9uTSa11vSHgjZXlEII",
	"QmA+L1EHMaq76K0vAl49Hd6AIoSaC4KXWiv9qOjzMF4w6s1S2s8Olu8lQ4ZQYYLJ7Muu9xlFGYVPKYRK",
	"N+pmiIVhxjlE1YXGlZaSYyoIUGn7YBpdUdVSZGEIEKl1wYiD5PMOOo8NJKIXVC1XiAW0UJoAFoohUsYl",
	"IhJhoZNdhMhg0/WjTP7EMho9bNEokx9jBaZmxUrKCKJiS8j1EnwiQn7ZFXyvbR7FRDGhkSa6wWpTCmbU",
	"Su+f8EAqqr1WiI9Gf9RQUo2ltKCBZreAL8z7PhScDjJzsIKprAj4lCqt1Sn5Qr5b096k2DfufG3pHnLH",
	"2PIpcJnn1NVZNJbZTFLtQlqs80hW9nSJsMsptUVO2b8DkodEr4sDwrFyUNQwS5evPTkSzsJjtdMW+ihU",
	"wkxseNk7KA4tMed4Xtzi9iFivizTuOw77ojLlBVIwreW1K/cACWvav1FZ3sQXl2OHFcLybcopvsvGfPn",
	"rJjP5hh9mRj2jN+bf67jx2opqzZWTlaLido8J8DN7VU/KIuDl3l9DGiwWjPZl0TIVQxYnnhzlitTs5bd",
	"Lt2llIYsN8Yc1FImy51+nYKcglE7FmPibjtEECn9BBGa4XBKaFl+x4wlgKnCqZQB4EGJgzazZujpxXtk",
	"bhSW85cQdCYdpO8x2hVvIczDKZEQyoyDV92YDILVTPP04r3wc4lJO/D1xjO18Ko3pFOYAccJUq0Roej5",
	"Ez80ez1z1ZpO0sxIV5GJsHp000qPSrzDLjCtpkcO3M6wnn3FerbdlGF9vDpJs1cmZ2N5tOcX7yuL7l1m",
	"B2CdpC0Ca458jqIffb+cqeGUNiSx3b2XBa6ayOJbbNuixLDPL94LhG8xSbRNhQUSAFQxgZLNN5d+9qtj",
	"KE2TdWyUJ9WsWCDvyiyk3HgLYNgmizP8R4h5JP5ZzNSPmLu5vHb9PpiGiyJh+7sZloSjinurulY+oSkG",
	"8U5UUcqMpmYCNJup8e2F65ZOQbr2kHAhR2MFe+fupWM6VPRtzOnVK/XL3F757kGmFon5F7FwbJT6Unnt",
	"kTN0FK6bGjsO663NnQqAjQjVQndTkphYi7lIiEJMzTLbq2rKkyI0NvvxFVWDt9Cd8vGU82pRFcahxVQ5",
	"gTLjVHmv9oo6FPkQCL2bYjOEcjWu6FgHN/StQN1LMhSBBD4jFBRq4XQZeeOdSIaUp2UtgOpiV+6+NqW8",
	"8kkuzZ2/8qXWFQVqSnUolIFSOm1AhHp1lPmhyTXCd6rlIi/o7iXk1vFCMaWlafx4C3wup4RO1DTyho4J",
	"KECkVz7OaOjfT2yOkNfiwTNwRrJu5nYM80eo04j8VlQ5zWiZkcdYwHCAgIYsgqgCDsUk8VtmpdOkRYgX",
	"tiJSUUcGYXOAoqx66/kSGnMsJM/qjT8T2zJ1cTzDmBjaUpkd71hy7Vgma8rr3f6Ym4iXlz+jG5ijCVDg",
	"1SFKOtIH/MKch7yA+Tr49uREjyMZcrI8nqMpmSgDnnEtt8BvSQjCO6BL+Foc6b3Iy/tIEm+3LvcrxMNk",
	"h/tiE6UsLh3X+iJ7Cd/ST65M58H7RwFliTAuDl5UmjMHPPog2SiR+s33UbTpwjxXK0V3HLu82urLdxAQ",
	"0Xhuv8Cq93ObtOe1Fk0qHyIxImrrTBKIlqni8v3WALHZdi0X5LamaL6BexWBSxts5hy9tGHlnZnkdmq1",
	"xHtz6a/ulyrtqgRAzIWEWTmM4IssuQzHVUEJ1cpsoToOcYe5nB+MCaM1lHNJkqtpwMQz0+6+SKJc18OG",
	"UO6LJMt1PV6YdvelLMxVU7WNzEQjEDeSpQfuRoxnqnke5yJQm7jpjI6lZdEDXJnsz6tgvTax881JlVO5",
	"wKGWVWqs8Fpd0yBak8tvniy7tvWby0qW6yI6rwgls2xmQkmqVRHNlEzt42aLVZBWOuu+zNmVtyEW23sy",
	"ahvM7kO1y+LyuWkvwdbkq125D0uILAYmsUSqqw6ImfhjmU56Tyx73OXU4FYp5NkKMJ37XXCTFbzC9d4w",
	"J7ipL653SJ8Tnt4ObAkkL1OfX9wOEDYNvDJbArAuaFaGtUkcoYSiZwZ1JRw9iLzIm5qzIfQqE1If9tqy",
	"Oc9eX7q7Fkq7MJrMUcLugOsTXBROMcehso5aLu6HGEfTeToFKlpI3/zXXjLoWzdyinDRSTXN48000uNK",
	"NGNCouFhCbYSyAToRE4ViWb400v9R3A6PGwFM0Ldnz3fqVgpj9dDgNpTuG85flKa09YW0iIMXxRlOjfB",
	"Q9P0B7Eu4rqYn9uYi5110ziOYVFyPr9wYQyXtVsnt+Z77lGVVn+Jcb7NiEiOVT7X1iLZ7RgrFr1Kthoz",
	"zx7c1gpIKcXaR6AlCHXH1pxl0u8SV8GYdnVQRDamINdDMe3qoLgccO/JUO6Pf3h59roKoTgTKohc53Dn",
	"9Pge3O3yXFarmhXstsLL/hpKZmc6YoEUdfK4gjJrjx02vi1RKVuxbBrkTpFnTG3wk3Gmo83upogz7DgL",
	"b5RXYOvS+Cy53H3yeUDmzNlcCal4KkLHyIlQZqZiBH0yHROqLT5AKQ5vlKmpbDssKxhBNMVSJ+Xrwjh+",
	"lF7kftwiSsbj0dZtGawpquMDVqpVoG9Rl5mydKbb8GKB4UZfxM6o+J9K2fs1VRFcgr89ctAbkr6xbA4Q",
	"lF9jottiWYqWCwIsDnMeq3FcTIOaWwjWDC8NKLI0ZVyK0lmjBWmuBDIKSExZlmjzrrxB6nCaKeErrA+m",
	"eUF5F2lCQmLOPabAladxRX2DjrGAtnYxnHsijCkppyAAzaw1WxpWYYRwga1W5iDDzhX1XKxYFPFFql3X",
	"rt+LUjWl5diimUV+OEUNe6sf76Zgjg6020UEKqz55VVU38Kaw4PCSvlBlO180z7j9s6b/xBhMTpQjFM/",
	"4zpdZr5+0W1uG6PaoLm1PV3qvixKpfXFY5aVBWiZLuW6HesRzvVExfFr1rfEozs7q8uxryfSOzvQCn7N",
	"z0AX1XPhIVSme11rwK8MLeTFSRruriVG92yuy5UxvLq7Whfje/I7lya4tbT4Ia0l13rr8KufvCylyl/Y",
	"VHzP7RzGpTF2iDvh1yW4keQ4tscGCz6XTeevheZA+GOXeW2GjXL91QTe6p5ec2VF+3o8NSYNJqyLSPig",
	"AI1c7LsAWBOxNdUnvK+q6PBUIziLAVcNtKURbMQGzfSBrXXy/SoFO9MdKYYytGa0W68hTA2NjQKspRob",
	"Pi7KP+f3pO0iuk2rqMsB5h++7cqV7NhYNoNKaY+ad7D014p6cMjJMFV+XZR6sFpYwIIOpREt5i1D2EZr",
	"Whsa8T0v9T2ESfwz3J0QrIyg7KXg+5SCtcEffwWdhqZqTbmtNVZrY8n83oRyywhmDYytDNXVwDfkhm0Z",
	"oZYJ9LNx/ltD7/IDX3tS7kKjxcWFZhlsBkjDDCD/cqgBaxPtiofyfhD1BxfeZ26alDSw454t9XeRZd+8",
	"bSetdKTE4bREOSTZTiixjJGHkbShPcsSSdIE0KuzpwfnF+7sGf1D273/RKmihsI1xUIgOeUsm9gTdnds",
	"ofRc/X6yvCBPz5+99fklpZtQOKw9cFcQXp09zRFdAWgxH6deEa9fzBVyaNknx0iTbANpXL1utbJpu6zD",
	"buMDg6pI6dX4dG469vThevGHH7ELbyGWFYJpiowgxX15F5/nZyu51CbLsfxIDuECaGd9FNeBrmeOemfN",
	"r/C+bf/MzcjlvxWlYBr2M+3XWbI54NV0rd9ALX+ssVyL2kQrskytCbriZl1+Q3Y9Dc7dVSFaOixpLFP5",
	"saNXTtaD8ciXp7BRE0iX5T4OraJkke9Guvri7v8Im43QzrMRKicJ5UMMxpGB5A52UJYyihKc0VDf4TFN",
	"lYzOJaxV5fmSu2UrLcUaZstZvZ7ddBPPCVlRJsnvTZhcgNImup7pivpKXpCFYmwI8b528pW13iYOXWfD",
	"LTgCDzbmlpnyUWzgZZrU7rQrfCBttH0fvk8+kwdEIaow9jp7r7MfW2c38IJtzbiNJL/W7fVc5sZRpI9j",
	"cHJR4eFdZcXA7NaWQKieEWvfOOWQp6O4tJL8v05ovcGEjevhLGerAwVOQlvPaQZC4Am0lq5bM5zJad9j",
	"sPuhniEJXICFapgFwacU08hcKNZC//O7dxe2ieLTDtL1t4S+722e0bAN35yp0av6poXGmbkabuCCvWms",
	"8OMEJOZzV6NPATeJXGcX5wIxW3ZDp+cyAQ6uSeozY1VDmIvF9co1kz6a2zZBa6n+UUbtjRVQfU1u8Ed7",
	"YO5g6mJoQWuxbJiEWco45iSZf8xonrBf6piP6n6YcEzlwqj6NzdkuciVUggJCaXOzpdTFn1UX62TuwBk",
	"BhHBDkhR6s4Xx/VUfPKksOiHlC2n2UyisasSpyGsNy7qy6tdP0xKitsFL/EYkg+mYqrnPWh9T/5FNgZz",
	"vyZRrZEuqtoqXWrTmaKK8SrFmOx9qhBTNIYrSmgEnyDPHlbCrrhfCxuWErga8v//u9senbV/x+0/r//x",
	"36fFX+2PnevP3dawd19q8c///i9vGmpzQpSL2q5wR01k7U2si6w+7n2exdt3i2V3vVeAS23KKcmVyp5j",
	"SBidqA1wPeMtDLrMbdebkXm9w/8YFG64uMs0X5Fkbg9bFhPNt6Z0MdSDibxkT3vu5lkM3W5rBVxXY0oS",
	"tW8Us+CAI1ME4o4T7w29lRqwUput9MleumSpsUOSOcLZZKaW2NxIxjO7F8+YzoeiEj7JlTXhdsQtXp14",
	"7ypN72wYiSf59dgyI5iadNut+IWnXnYN4+bttNWgc9/KRRULcyCjN5Td0YVq3OU/9RYawcJns2ddP0wt",
	"8y+lImrzuD8v8bopfWyKrPuIK8kMqnrAlJlNQJr069zHiLCEtmpeU+DCs5Y73nM8DONRTItNPBqqtaGG",
	"0Upl09qd1q3w+ugzTCUJnRuxYEzcXl1F//vqqlP6z0MNhhqGeUwDYQVXlp4G8LGkLjV8N2XItquwp79k",
	"S+UtgeZsbgdozuZ1IbiMkv9k6+uBzlikXZm1M8/SqNnMHcQ1M8fVeVvwTeftrQVZJnkDEdMJJbl42VqK",
	"Dilrc/+RCVuu12QMVMo7XVFM59W9QLWZAk7k1DqTxu1UZn9MJIo5myGsPtEIa3fwiuYY2OyVcorBVj6J",
	"xBNv3hLmYyK58nMlnhj7QKGrnRDPLdKaigyWrxwIf4ac3w1Sa68/uSiexJP1hl3lMYrrB5NmXfRYWSmN",
	"A0cbrspScKkU77tUIK2nooMn1brDyyi/MTlSjBbVxmzcYwyY67PPG6CoWkFZy1fC7kwQywYl9JenLIKl",
	"H9/zJDgNplKm4vQgL6vTqUy7w/jkwKB8cNs/qPQPWoGOWKjh1OQVRlvA1P0qBxn6k8mkJDT2ZKo91UWw",
	"7FXuiIiQ3QKfm1JsLDOpZaYCk+ZAIhMFt5QBY9NvLk0jZdFXXkzvdnqdnstGxikJToPDTrdzaPbNqabv",
	"AU7JwW3voOw+iYPPFZ/w2f1BUSPQU5ACUzxRvr67iZ6XjULoPO9Xyp0ShE4SrbZNdQ/sfrFJVKaQDQ2h",
	"c0W1AkzIjEiBxgkWEnEckUy4yALcgqlyikuvEaAE8I2uwU8oEmxmqrQLhG8ZiQQaZxPV/4pWTWQbQlW0",
	"noD0hRWlNmvsPNWUtJ+pD/BpxS9XMJjjff36zHOQZyn50HtTpvObCpULWulKcSa4pund73brpDxvd1Au",
	"AWlLnt+3gkGTrg973UOP0tvpKN4C7nqcw52Os/xYxn0rONoxyVa9x1DWrtqc9OvVf1/r+EBRwqvW9Cya",
	"HFRluKieoUE1lHtam1VppF4U93QQcsmE7p2Foso24ygvoYIoixa8U6sFPrw8e925oq+ZBGPZ6CIduXZw",
	"97aIQPpVByqTOcpjuigtys7NWwiLUl1ThLmOSUrQMXVdgFJtpapLSiDUm/1yUTqvFlB7c+Vy0sZynudc",
	"biPlSw/072V8L+MPk3EblRQHn1188u+34e+I6q21XXMSl9eqFaTMZ/E/1Y42wojCXSnRjy5k3VY10AUT",
	"a1WQrZ4qLhw2C7aHFv4nLJrXC4lrQqBcDtqcJt4vabZeY/tlvtdsf0nNtjN9dPDZccr5s/s8Wutx5Z/p",
	"3ys5ssq1wnReiqBgIVhIdNRIH0QQuSxRBtADZOo8R3h5z+/vdLWWnhTcC9E2QjToDnY6yNKTXt+0CfI3",
	"du8dquWKyBsb+Ftqgu5+j9xb/1/TDl3fq9h5H8XVqGztf+/Yw3fJCI38mFI6404dl0K1VgIsG7oyedm5",
	"B3gyOYy9kt47Mptqu4PPrh5pM+9mtUzt0HVxUvXaobf3ZfZytHM/4+93oGD8jnQ6JyKsvqb7OI5HAznu",
	"7ve4vSPy/dmf67vlW+sXcF9MlV3vy2W3JAKhlEXbPtqm26KZ1oAzoLKlVIoOi5hMwpCl5qK0DYtUAppT",
	"EsEVNRlAtkyuucQFOJyazKAOQmeTCYeJzRoQaIpplLjX71Nsld94bh57Y1RyliTAO1f0wjxtT3MlaiaG",
	"Qkwp00VpgcaMh0Zj2hm1jAq20zvTeSE4DDXeOEnmVzQT+buFT34Q5QoKCD01v6tpK21eQveWYHMrS98b",
	"Epm+YNVCgiEifxBXlMyU8sZUunQUNQlhHjgr3adRuLCMStEyb93TyFwi1GBFrao+sxi384K3toCxJYnv",
	"obbHUeK/GObaRnMbXPeKe6+4v6nAQSZ9ry/KJS3ZRMousp1L2YZhBCdkdVGEvae0F+qvHXFww0/yLH6/",
	"Q7ZYqwJdVitn4FAK5R5hZB/NQjHhcIeTRIuqO+3R2fjWskDKeRqzTB/HRohl0vxRLp/7lw2ALhcseaQ4",
	"6GV1gbdQYwsl9x4QE12AtNdTez21nZ46+FxhpaZR0nVCt8NAaVXsLqvY7oOmexF7hKDp19mjV92jWCNv",
	"u3KENxS27n6n2ovRXze+ubA1NnCx3+ucVtFAYnflVK+X2McxUvf77F5BfOum7IEujd/YFbeV9L/iZq+z",
	"ofxYfZ0tX79HsIN93zxrsJft/eb/F9n8N41L5a+efJHgVK0UP8gW0I+F7CxopaHtNcJ+t9/tbn/wWf1n",
	"uzhWjZB+qWCW2SU19vu41l4CHz+u9fUNXl90q0YKv5y9WyeC3f0Wtxewv6vRu76v2Xe/wFVAW+t9lV+f",
	"F4P/K597u/cQHs2lMGTeym8w1fUf5CwYEHv1ufcQNlQMyjXQb300dgL8krRTu19jdmnx2pv3e/F5FPM+",
	"3/dWWtt+dt+dgb2G17t77b83nv+SxrPh+O1MYFOASvheHtAfUAQxoWq/MvVSETLVjE0u3wTYhON0SkKc",
	"IMZ1WZ6ETfSfKeZSP13UuaI/Ep3Ycofn5i0BYp4OSDmZEUlubU4KEeZdEsmKij5F3WSRhVOExRWtDJqw",
	"ECfQKmp3Cj21HwTioCkToXHCxojF+umgTAICGSqUcDh1ZVunWCAiBWJ31KQgRsA9RYVaOhABn/AsTQC9",
	"SYFeShze6ILNV9QBsNkkRaUTgQRT06YTYZ9WKdccRUUaSkJMziG+omKKOUSG5vnDt3dTLOEWOJpBOFVT",
	"nSmS5Y/wmEeJsLS93ERWH/uZEu96qbfSzZZNtlK3dtyvoQn3pQOXVMDBZ/MP9RN8MtOpr96hHwsWyDwt",
	"pRj5KnCd8uTfq0ALjGNEW+nc5uYqBTDrXNFfpyQB9PTs4o0WDkJj+zjLIjgloZDELUQkCjlOBWKZRO0r",
	"inUWHspEhhPURiQ2D5Hod7QYBVNwPaNRC91xHN7k8kzVjHS2sa5hlAl0B0hIkqghjXSajDU1og5MalHF",
	"CRKU3cUJvlmXD+xKfS9R5iGi9tau0o+La7SNCDrMXnsrku6Lgf1FioF9McvHqZCdaSLzcKNHAT21u7l9",
	"rjOvZ7Zqt9MZqrkdYEEbraQ0TqmCPdhcUmUZ5DpuB0L7k53ONrJq8f3ruid7+dm9/OjXTleIj/6+jfQY",
	"wM2FZxdb3rmZzFZF93TXvezsZadGdr7tRMrG9za3EjNPjuGDjqD3ly73IbRdeaebHLuukpK80RbSUZxI",
	"bhdR3svDXh7WyMP9/f8EAAD///wAcupVAAEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/main/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
