{{- range $region := .Values.regions }}
---
apiVersion: region.unikorn-cloud.org/v1alpha1
kind: Region
metadata:
  name: {{ include "resource.id" $region.name }}
  labels:
    unikorn-cloud.org/name: {{ $region.name }}
    {{- include "unikorn.labels" $ | nindent 4 }}
spec:
  provider: {{ $region.provider }}
  {{- with $kubernetes := $region.kubernetes }}
  kubernetes:
    kubeconfig: {{ $kubernetes.kubeconfig }}
  {{- end }}
  {{- with $openstack := $region.openstack }}
  openstack:
    endpoint: {{ $openstack.endpoint }}
    serviceAccountSecret:
      {{- if $openstack.serviceAccountSecret.namespace }}
      namespace: {{ $openstack.serviceAccountSecret.namespace }}
      {{- else }}
      namespace: {{ $.Release.Namespace }}
      {{- end }}
      name: {{ $openstack.serviceAccountSecret.name }}
    {{- with $identity := $openstack.identity }}
      {{ printf "identity:" | nindent 4 }}
      {{- toYaml $identity | nindent 6 }}
    {{- end }}
    {{- with $compute := $openstack.compute -}}
      {{ printf "compute:" | nindent 4 }}
      {{- toYaml $compute | nindent 6 }}
    {{- end }}
    {{- with $image := $openstack.image -}}
      {{ printf "image:" | nindent 4 }}
      {{- toYaml $image | nindent 6 }}
    {{- end }}
    {{- with $network := $openstack.network -}}
      {{ printf "network:" | nindent 4 }}
      {{- toYaml $network | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
